self-hosted-runner:
  # Labels of self-hosted runner in array of string
  labels: []

# Configuration variables in array of strings defined in your repository or organization
config-variables:
  - REGISTRY
