output: false
settings:

# To install all the required plugins:
#
#   npm i -g $(grep remark-lint ~/.remarkrc.yml | \
#       sed -e '/\s*#/d' -e 's/^  - \(- \)\?//')
plugins:
  - remark-lint

  # --- Linting Presets -------------------------------------------------------#
  # Must be loaded before rule and setting overides

  # Consistent Preset (aka C)
  # See https://github.com/remarkjs/remark-lint/tree/main/packages/remark-preset-lint-consistent
  # - remark-preset-lint-consistent
  - remark-preset-lint-consistent

  # Recommended Preset (aka R)
  # See https://github.com/remarkjs/remark-lint/tree/main/packages/remark-preset-lint-recommended
  - remark-preset-lint-recommended

  # Markdown Style Guide Preset (aka MSG)
  # See https://github.com/remarkjs/remark-lint/tree/main/packages/remark-preset-lint-markdown-style-guide
  - remark-preset-lint-markdown-style-guide

  # --- Git Flavoured Markdown ------------------------------------------------#
  # Add support for parsing GFM tables, tasklists, strikethrough, and autolinks.
  # See https://github.com/remarkjs/remark-gfm
  # Must be loaded before presets and rules since additional parsing may be
  # required for those rules to be applied.  Note that the default option
  # settings for the plugin correspond to the default option settings for the
  # rules.
  - - remark-gfm

  - - remark-github
    - repository: agios-ierodromos/.github
  - - remark-validate-links
    - repository: agios-ierodromos/.github
  - remark-lint-list-item-indent
  - remark-definition-list
  - remark-lint-no-dead-urls

  # --- Linting Rules and Settings --------------------------------------------#
  # See https://github.com/remarkjs/remark-lint/blob/main/doc/rules.md

  # Warn when list item checkboxes are inconsistent (C)
  # See https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-checkbox-character-style
  - - remark-lint-checkbox-character-style
    # - consistent                         # (default, C)
    - { checked: "x", unchecked: " " } # matches formatter default

  # Warn when list item checkboxes are followed by too much whitespace
  # See https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-checkbox-content-indent
  - remark-lint-checkbox-content-indent

  # --- remark-lint ----------------------------------------------------------#

  # Warn when horizontal rules violate a given style (MSG, C)
  # See https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-rule-style
  - - remark-lint-rule-style
    # - consistent  # (C)
    # - '***'       # (default) matches formatter default
    # - '---'       # (MSG)     matches formatter setting `rule: -`
    - "--------------------------------------------------------------------------------"
  # # ^ matches formatter settings `rule: '-'` and `ruleRepetition: 80`
  # # This is a personal preference

  # Warn when a bullet and content are not seperated by a single space. (MSG, R)
  # See https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-list-item-indent
  - - remark-lint-list-item-indent
    # - tab-size   # (R)   matches formatter setting `listItemIndent: tab`
    # - mixed      # (MSG) matches formatter setting `listItemIndent: mixed`
    - space #       matches formatter setting `listItemIndent: one`

  # Warn when the marker value of ordered lists violates a given style (MSG)
  # See https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-ordered-list-marker-value
  - - remark-lint-ordered-list-marker-value
    # - one     # (MSG)     not enforcable by formatter
    # - single  #           matches formatter setting `incrementListMarker: false`
    - ordered # (default) matches formatter default

  # # Warn when the markers of ordered lists violate the given style (MSG, C, R)
  # # See https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-ordered-list-marker-style
  # - - remark-lint-ordered-list-marker-style
  # # - consistent # (default, C)
  # # - ')'        #              matches formatter setting `bulletOrdered: )`
  #   - '.'        # (MSG, R)     matches formatter default

  # Warn when markers for unordered lists violate a given style
  # See https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-unordered-list-marker-style
  - - remark-lint-unordered-list-marker-style
    # - consistent # (default)
    # - '-'        # (MSG)     matches formatter setting `bullet: -`
    # - '+'        # (MSG)     matches formatter setting `bullet: +`
    - "*" #           matches formatter default

  # Warn when missing blank lines before block content (maybe except for lists)
  # See https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-no-missing-blank-lines
  - - remark-lint-no-missing-blank-lines
    # - exceptTightLists: false # (default)
    - exceptTightLists: true #           matches formatter default

  # Warn when headings are indented
  # See https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-no-heading-indent
  - remark-lint-no-heading-indent

  # Warn when linebreaks use an inconsistent style
  # See https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-linebreak-style
  - - remark-lint-linebreak-style
  # - unix # (default) matches formatter default

  # Warn when hard tabs are used instead of spaces
  # See https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-no-tabs
  - - remark-lint-no-tabs
  # XXX: vim settings avoid this issue

  # Warn when link and definition titles have inconsistent quotes (MSG, C)
  # See https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-link-title-style
  - - remark-lint-link-title-style
    # - consistent # (default, C)
    # - '\''       #
    # - '()'       #
    # - '"'        # (MSG)
    - false
  # XXX: The formatter uses single or double quotes depending on the contents of
  # the title. There is no setting that will accommodates this, so we disable
  # this rule.

  # # Warn when more than 2 spaces are used to create a hard break (MSG, R)
  # # See https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-hard-break-spaces
  # - remark-lint-hard-break-spaces

  # Warn when lines are too long (except headings, tables, code, defns) (MSG)
  # See https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-maximum-line-length
  - - remark-lint-maximum-line-length
    # - 80    # (default, MSG)
    - false
  # XXX: Some sites like GitLab really don't like the hard wrapping and want
  # paragraphs all on one line, so I turn this off and let VIM to do
  # soft-wrapping instead.

  # # Warn if fenced code blocks do not have a langauge flag (MSG)
  # # See https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-fenced-code-flag
  - - remark-lint-fenced-code-flag
    # # - ['bash', 'js', 'markdown', ...]
    - allowEmpty: false # (MSG)

  # # Warn when multiple top level headings are used (MSG)
  # # See https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-no-multiple-toplevel-headings
  - remark-lint-no-multiple-toplevel-headings

  # # Warn when shell code is prefixed by dollars (MSG)
  # # See https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-no-shell-dollars
  - remark-lint-no-shell-dollars

  # # Warn when headings increment with more than 1 level at a time (MSG)
  # # See https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-heading-increment
  # - remark-lint-heading-increment

  # Warn when the first heading has a level other than '1'.
  # See https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-first-heading-level
  - - remark-lint-first-heading-level
  # - 2  # example for, say, a markdown fragment to be included in another file
  # - 1  # (default)

  # Warn for empty URLs in links and images
  # See https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-no-empty-url
  - remark-lint-no-empty-url
  # XXX: better in a post-commit hook

  # Warn when duplicate headings are found, but only when on the same level
  # See https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-no-duplicate-headings-in-section
  - remark-lint-no-duplicate-headings-in-section

  # Warn when definitions define the same URL
  # See https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-no-duplicate-defined-urls
  - remark-lint-no-duplicate-defined-urls

  # Warn when HTML nodes are used (except for comments)
  # See https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-no-html
  - remark-lint-no-html
  # XXX: depends on publishing target

  # Warn when the content in paragraphs are indented
  # See https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-no-paragraph-content-indent
  - remark-lint-no-paragraph-content-indent

  # Warn when full reference images are used if they can be collapsed
  # See https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-no-unneeded-full-reference-image
  # - remark-lint-no-unneeded-full-reference-image
  # XXX: limited utility

  # Warn when full reference links are used if they can be collapsed
  # See https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-no-unneeded-full-reference-link
  # - remark-lint-no-unneeded-full-reference-link
  # XXX: limited utility

  # Warn if too many hashes (h7+ “headings”)
  # See https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-no-heading-like-paragraph
  - remark-lint-no-heading-like-paragraph

  # # Warn when file name start with an article (MSG)
  # # See https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-no-file-name-articles
  - - remark-lint-no-file-name-articles
    - false

  # # Warn when file names contain consecutive dashes (MSG)
  # # See https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-no-file-name-consecutive-dashes
  - - remark-lint-no-file-name-consecutive-dashes
    - false

  # # Warn when file names contain irregular characters (MSG)
  # # See https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-no-file-name-irregular-characters
  - - remark-lint-no-file-name-irregular-characters
    - false

  # # Warn when file names use mixed case (MSG)
  # # See https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-no-file-name-mixed-case
  - - remark-lint-no-file-name-mixed-case
    - false

  # # Warn when file names contain initial or final dashes (MSG)
  # # See https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-no-file-name-outer-dashes
  - - remark-lint-no-file-name-outer-dashes
    - false

  # # Warn when the file extension is not '.md' (MSG)
  # # See https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-file-extension
  - - remark-lint-file-extension
    # - md  # (default, MSG)
    - false

  # Warn when references to undefined definitions are found (R)
  # See https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-no-undefined-references
  - - remark-lint-no-undefined-references
    # - allow: ['...']   # example to allow, say, `[...]` for elided content
    - false

  # # Warn when unused definitions are found (R)
  # # See https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-no-unused-definitions
  - - remark-lint-no-unused-definitions
    - false
