# .github/workflows/release.yaml

on: 
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:

      # See: https://github.com/marketplace/actions/thinkdolabs-curl
      - name: Downloads the organization .env file
        uses: thinkdolabs/curl@v1
        with:
          args: --location -o organization.env https://raw.githubusercontent.com/agios-ierodromos/.github/main/.env

      # See: https://github.com/marketplace/actions/environment-variables-from-dotenv
      - name: Loads environment variables from .env
        uses: c-py/action-dotenv-to-setenv@v4
        with:
          env-file: organization.env

      # See: https://github.com/marketplace/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@$v3.3.0

      # See: https://github.com/marketplace/actions/go-release-binaries
      - name: Release Go binaries
        uses: wangyoucao577/go-release-action@$v1.35
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: amd64
